### ISSUE TITLE
Samsung Smart Refrigerator and Mobile Comparability 

### ISSUE THREAD

**Issue by PolarisWasInDenial** [IronShears/ironshears.github.io#1]
When accessed on the currently deployed build of this project, text is sufficiently small to be nearly invisible on Samsung Smart Refrigerators.

**Comment by IronShears** [comment]
I am not fixing htis

**Comment by IronShears** [comment]
> When accessed on the currently deployed build of this project, text is sufficiently small to be nearly invisible on Samsung Smart Refrigerators.

I am not fixing this
